In [1]:
import pandas as pd

In [2]:
customers=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vTEgwFZoArQxzrq0jWWDQVBppTGYUV_Ka0N0jbDG5WIS-rIOv6SRD-ew93imnCK3ExrGBuS5J7lhb5f/pub?output=csv")
orders=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSt3FK3N-slM6ExBo-Wz2NSHwXAmxwvUCTHelAIsUkylUbtq3RTUpWIcKPfHS7ZYdzmEq13z4DnYslm/pub?output=csv")
order_items = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRVK_VN5jeWgh7XnIQVB5QuObbuVP_Z3gVjS5rpt_oj6eyDrS4itg0LHiOJRYH1JMDVHqwM1eeSN4XX/pub?output=csv")
products=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQ9acK5QmnoV3JSiwEpd1smjx99OmCP-XSNFBqUaiahkxf2C3GH4eJQ6n1KMf4Anv2ti8LjoIYPjv0Z/pub?output=csv")
payments=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQlbhQCuXYjxFmIeTSeTFXhGQMGe5f9eP-svg8-ucyrfpoEQC9rt-drjoqkLulkdp3jMAjDwvOOWYol/pub?output=csv")
reviews=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQDgZ9y9wIfUpD7jZqd0Hz0Oe5cePVzPljTNZUP0PZEysakMjvUugbJef3bOyX_6DwGpzkOqvWW8Cp8/pub?output=csv")
sellers=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSjhMFqKZY_YcZqvsgEzqNxgxB7P1UlZi1hIa8E2t3VUa7ueVyNWHDx7EDv5AXwq_bNxuNOi14cwC5p/pub?output=csv")
translations=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSN6bxQKqtTzRrVUx2sojqirjBicTYuvh3UaVJBuVAi7fyrj_NtMQ97jPwaGcVn3NVokjQIPsCjal8u/pub?output=csv")
geolocation=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vTstVWkA8eB8RqVhHABsJ_NpMMvK9B903qZJEZmgny9TgJvWfk9GqOS6Z0ZBEQVOU_DhAQzXdNU9T7Q/pub?output=csv")

In [7]:
order_items.head(10)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23 03:55:27,21.90,12.69
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.90,11.85
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26 18:31:29,145.95,11.65
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06 14:10:56,53.99,11.40

In [70]:
# Merge customers with orders
customer_orders = pd.merge(orders, customers, on="customer_id", how="inner")

In [71]:
# Merge with order_items
combined_data_set = pd.merge(customer_orders, order_items, on="order_id", how="inner")

In [72]:
# Merge with products
products.rename(columns={'Unnamed: 0': 'product_id'}, inplace=True)
combined_data_set = pd.merge(combined_data_set, products, on="product_id", how="left")

In [73]:
# Merge with sellers
combined_data_set = pd.merge(combined_data_set, sellers, on="seller_id", how="left")

In [74]:
# Optional: Merge with payments (for spend insights)
payments.rename(columns={'Unnamed: 0': 'order_id'}, inplace=True)
combined_data_set = pd.merge(combined_data_set, payments, on="order_id", how="left")

In [75]:
# Optional: Merge with reviews (for sentiment)
combined_data_set = pd.merge(combined_data_set, reviews[['order_id', 'review_score']], on="order_id", how="left")

In [76]:
# Optional: Translate product category
combined_data_set = pd.merge(combined_data_set, translations, on="product_category_name", how="left")

In [77]:
# Rename columns for clarity
combined_data_set.rename(columns={
    'product_category_name_english': 'product_category',
    'customer_state': 'state'
}, inplace=True)

In [87]:

# Quick check on the merged result
print("Final shape of combined_data_set:", combined_data_set.shape)
combined_data_set.head()

Final shape of combined_data_set: (118310, 35)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,payment_sequential,payment_type,payment_installments,payment_value,review_score,product_category
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,13.0,9350,maua,SP,1.0,credit_card,1.0,18.12,4.0,housewares
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,13.0,9350,maua,SP,3.0,voucher,1.0,2.00,4.0,housewares
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,13.0,9350,maua,SP,2.0,voucher,1.0,18.59,4.0,housewares
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,19.0,31570,belo horizonte,SP,1.0,boleto,1.0,141.46,4.0,perfumery
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,21.0,14840,guariba,SP,1.0,credit_card,3.0,179.12,5.0,auto

In [91]:
# Save to the same folder as your notebook
combined_data_set.to_csv("combined_data_set.csv", index=False)